### ISSUE TITLE
rtlibとrtutilの合体

### ISSUE THREAD

**Issue by gx1285** [free-RT/rt-bot#10]
元々はrtlibは配布予定だったので合体する。
名前はrtlib/rtutilどちらにしようかな？

オリジナルは @yaakiyu が  にポスト

**Comment by yaakiyu** [comment]
管理者の投票により名前はrtutilになりました。

**Comment by yaakiyu** [comment]
いっそのこと「util」という新しいユーティリティ機能パックみたいなの作っちゃうか
んで完全に移行出来たら「rtutil」って名前に変える

**Comment by yaakiyu** [comment]
完了。
