### ISSUE TITLE
discord.pyへの帰還

### ISSUE THREAD

**Issue by gx1285** [free-RT/rt-bot#14]
開発再開したので。

**Comment by gx1285** [comment]
discord.pyもスラッシュにコマンドフレームワークを対応させなければ。

**Comment by gx1285** [comment]
作業は`slash`ブランチで行うことにする。
それとスラッシュ対応させるライブラリを作る予定なのでそれを使う。

**Comment by gx1285** [comment]
あとrtlibとrtutilの合体とかも

**Comment by yaakiyu** [comment]
#48 と被るのでclose
