### ISSUE TITLE
botの認証

### ISSUE THREAD

**Issue by kuroneko6423** [free-RT/rt-bot#28]
Botの認証申請文をどうしますか？
現在ステータスしかないから認証しようがないんですよね。

![image](https://user-images.githubusercontent.com/42853476/162387752-6dd7ee32-a9f3-4add-b92d-6238a03ed9f8.png)

**Comment by waki285** [comment]
ちょっとくろい話: モックのスクショでも案外通ります

**Comment by yaakiyu** [comment]
認証は稼働してからにしよ

**Comment by HardSmoothy** [comment]
そろそろ認証申請しないとまずい気がするのだが...

**Comment by yaakiyu** [comment]
管理者間でいくつか認証前に必要なことに関する話し合いをしてた。

**Comment by ysmreg** [comment]
認証どうする？RTの無料化は達成出来たけど

**Comment by yaakiyu** [comment]
僕はどっちでもいいよ
そっちのやる気次第
もしくはテスト機達を開放して使わせるって手もあるけど

**Comment by ysmreg** [comment]
私は認証botにしたいって思ってる

**Comment by ysmreg** [comment]
テスト機を開放してもいずれ認証が必要になりそうだから
