### ISSUE TITLE
新アイコン提案(#提案より)

### ISSUE THREAD

**Issue by gx1285** [free-RT/rt-bot#29]
![image](https://user-images.githubusercontent.com/78240988/162417623-3aa1025d-0fcd-4c7f-afa9-3619bc69cfaa.png)
[元提案](https://discord.com/channels/961521739748212776/961604402177773579/961927775210573825)

**Comment by kousakirai** [comment]
今のやつでよくない？

**Comment by sonyakun-python** [comment]
たしかに

**Comment by gx1285** [comment]
閉じます。
