### ISSUE TITLE
ウェブサイトの作成&利用規約とプライバシーポリシー作成。

### ISSUE THREAD

**Issue by gx1285** [free-RT/rt-bot#33]
- [x] ウェブサイトの作成
- [ ] 利用規約作成
- [ ] プライバシーポリシー作成

**Comment by yaakiyu** [comment]
ウェブサイトは作成完了。現在freeRTに対応中...

**Comment by yaakiyu** [comment]
まぁとりあえず終わったってことでいいでしょ
なんか問題あったらfrontendにissue立ててくれ()
