### ISSUE TITLE
headdingとextrasの置き換え

### ISSUE THREAD

**Issue by yaakiyu** [free-RT/rt-bot#34]
そこまで重要じゃないんだけど作業系だから暇な人はやってくれ。

# 内容
全部のcogを見て、それぞれのコマンドの先頭には`@commands.command(...)`があるはず。
この`...`にheaddingとparentという引数があることがある。この引数をextrasに変えてほしい。

## 具体例
```python
@commands.command(
    headding={...},
    parent="..."
)
```
これを、
```python
@commands.command(
    extras={
        "headding":{...},
        "parent":"..."
    }
)
```
こうしてほしい。
上の書き方は非推奨。

あとheaddingとparent以外の引数は関係ないので無視。

**Comment by kousakirai** [comment]
ok任せろ

**Comment by kousakirai** [comment]
サンプルのスペルミスってるぞ()

**Comment by kousakirai** [comment]
extrasがexrtasになってる

**Comment by yaakiyu** [comment]
あ、()

**Comment by yaakiyu** [comment]
これで全部終わった?

**Comment by kousakirai** [comment]
終わったから閉じとく

**Comment by yaakiyu** [comment]
rtlibとかのコードにこの旧バージョン用のが入ってたからそれを省けるようになったね
