### ISSUE TITLE
Discord.pyで動作できるようにする。

### ISSUE THREAD

**Issue by gx1285** [free-RT/rt-bot#48]
Discord.py v2.0で動作できるようにする。(稼働後にmarge)

# Pull requests一覧
#47 
#77
#73

**Comment by yaakiyu** [comment]
d.py2.0の更新(freeRTに関係ありそうなところ)を調べてる。結構多い。

* Client.loopはasync外では使ってはいけない
* 非同期の`Cog.cog_load`関数が追加
* extensionのsetupとteardownが非同期に
* `Bot.load_extension`, `Bot.reload_extension`, `Bot.remove_extension`が非同期に
* `Cog.cog_unload`が非同期に
* `Bot.add_cog`と`Bot.remove_cog`が非同期に

**Comment by yaakiyu** [comment]
* Viewのcallback関数のとる引数の順序が`(self, button, interaction)`から`(self, interaction, button)`に
* `StoreChannel`が削除
* `ChannelType.store`が削除
* `StoreChannelConverter`が削除
* `Guild.bans`がAsyncIteratorを返すように(具体的にはfor文ではなくasync for文を使わなければいけない)
* `on_thread_join`イベントはなくなり、`on_thread_create`へ
* `View.on_error`の引数が`(interaction, error, item)`に

**Comment by kousakirai** [comment]
そういえば：d.py v2.0にするならJishakuGithubから落とさないと使えないよ。
あと、Githubから落としても謎のエラーがたまにでてshコマンドとかが使えなかったりする

**Comment by gx1285** [comment]
https://jishaku.readthedocs.io/en/latest/whatsnew.html#version-2-4-0
対応してない？

**Comment by kousakirai** [comment]
俺の知ってる限りPypiに上がってるのは旧バージョンだった

**Comment by kousakirai** [comment]
あ、違う。Pypiにすでに上がってるわ。仕事早いなDevonさん

**Comment by yaakiyu** [comment]
freertのソースにない(つまり関係がない)項目は線ひいといた

**Comment by yaakiyu** [comment]
そういやまだスラコマ動かないんだった()

**Comment by yaakiyu** [comment]
スラコマ以外はd.py2.0への移行ページ見ながら全てチェックした。
おそらく大丈夫なはず。

**Comment by yaakiyu** [comment]
スラコマに移行した。
やっと終わったぁぁぁ
