### ISSUE TITLE
スラッシュコマンドの登録個数制限対策

### ISSUE THREAD

**Issue by yaakiyu** [free-RT/rt-bot#62]
スラッシュコマンドの登録の制限がかかってしまうため。

**Comment by tuna2134** [comment]
ん？
なぜ今のままにしない？

**Comment by yaakiyu** [comment]
d.py以降の際、めんどくさいモンキーパッチをできるだけ少なくしてハイブリッドコマンドに直すだけにしたい(更新が大変になるため)。
そのとき普通にコマンドを登録するとコマンド数が100を超えて制限がかかる。

**Comment by tasuren** [comment]
後いくつかのコマンドがネストしすぎてるグループコマンドとして登録できないかも。
グループコマンドのグループコマンドのグループコマンドのグループコマンド...
って感じに深いやつは登録できない。

**Comment by yaakiyu** [comment]
そういうコマンドも洗い出さないとか
(ちなみになぜ今までのカテゴリ式スラッシュにしなかったのか：あの方法コマンド1個がみにくかった())

**Comment by tasuren** [comment]
Kusa

**Comment by ysmreg** [comment]
スラッシュコマンドが100しか登録できないから100個だけスラッシュコマンドにして登録出来なかったのを普通のコマンドにしてもいいかも

**Comment by tasuren** [comment]
音楽プレイヤーとかの主要コマンドだけスラッシュに登録して、それ以外は`/rt run コマンド`で実行できるようにするってのもいいかも。
(`/rt run コマンド`はもうある。)

**Comment by yaakiyu** [comment]
なるほどなるほど

**Comment by yaakiyu** [comment]
(そうしたいならどういう技術を使えばできそうか言ってくれると助かるな((

**Comment by tasuren** [comment]
どっちに対して言ってる？

**Comment by yaakiyu** [comment]
どっちも
でもtasurenは考えるのめんどくさいなら(新RTで忙しいなら)いいよ

**Comment by tasuren** [comment]
`/rt run`コマンドはもうあるよ。

**Comment by yaakiyu** [comment]
主要コマンドだけ登録する方法
hybrid_commandにslash登録しないみたいなオプションあればいいんだけど

**Comment by tasuren** [comment]
音楽コマンドとかだけ`hybrid_command`に書き換えるとかじゃダメなん？

**Comment by ysmreg** [comment]
音楽とか、ヘルプとかafkとか天気がよく使われてるイメージだから、それを書き換えてhybrid_command化してそれ以外のはcommand使えばいいかも

**Comment by HardSmoothy** [comment]
サブコマンドグループで囲うのはどうだろうか...?
サブコマンドグループ(100対象外)でサブコマンド(100対象外)を囲ってテキストコマンド(100対象内)をその中に入れたら....
但し処理の書き直しが必須になるので注意が必要...

(API情報を参考にしました)

**Comment by yaakiyu** [comment]
いままでのRTがやってたのがその方法だったんだけど、
コマンドが見にくくなくから嫌なんだよね()

**Comment by yaakiyu** [comment]
hybrid置き換え大作戦やる！！

**Comment by yaakiyu** [comment]
主要コマンドのhybrid置き換え完了。
